// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class uimodel : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207260946561_uimodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7n0jiu3npSD+v1U1fyNW5g0JU/k1IG3WTiBQVpDsay+kC+iT6umTjoqS1q/ztiM0JghOXScScI/tN51hDUEK/fg+vM73N0B1qjaGmf0uRihLEvvd47uSbtAPHt8dyEs8/iJbrWhOvDyFfpK+liTF"
                       + "yfbr989ELATG3WkQ3nQn0PZEU5hd5J1vIQozUQZPszabZGCTk9mi1+xGBjD9xPmga8cc8c17+F15rZuxsTzTgeLo+IyGtiC7xKPUMRJOA8kYfff1NCuzOmIaT6pyvVgOmddNb4cWy4cTfvP+EMUKxSDKN7eHaO2ID8x+eHs4zqr5gNynt4cUMQg+yMjXXwO2Z/CiwL3v+9Af3+0wWpefPWWqLUMx0e+dnLyXFG3IZby3LG2EdQuJuuH9n79yFU1GBKwWa/C14A/xcrTF1+rB5hB8+LHvvxZ0lx0YAO8a3B7+N6XXjC/lgzGf3R5K3MOMDjdo8TV68AP7AXp+LfjfiOa8EfoH6PyfI608EK6/tyYehHMLLbzh3Z+/Gvib80i+KV3y/34ZulG7/Kzpr29Gzwbhrw8q+OKHrDt6IWO3ie1dP7F/25BRwzVRFe69/vp2L36TJh+lRKjLYobY7fV10+aLMRqMX/+i8nVe0wL+ST7ex6q8afZFtizO86Z9U73NKc3H33UWym8dntpcX9PMyv+XrpYX4Isbc5zvmYyJZSyXl1k9nUOT9bJH75cuiiUkeRTviWQnkfh1QHQzml8HxmAa8Bsj2HCy82t2ceuM/oYg6Ue8vQn4h/J2NMb6hnGNh1k/e5101nN/NrroLtd+Y318A7omzG3XeVa+N4hN6f5vbKjRcOub7uOb1mg/+2r51jrz53AV9OevvvwmDPk3IOP/H+TrnyMt8w1ow8iK4S3gvN96YX9VKUTJBk9W+G9cL5S45rOPZpOK0BY8b7uYGPpjNy4ixrrqNLmhw1uuM8bHpF93enmPdch+8Pj47iua7mIhU/eYWLO4cCAeE8ylKBQH1LQ5W55XhoNogD5GpkmHwb7IW0pztdlx3Rbn2bSlr6fkwPCq+k9m5ZqanC4m+exs+eW6Xa3b46bJF5Py2h/v47ub++fF1hDnx1+ueHK+iSEQmqwsvlw+WRflzOL9LCIYAyAgAmpOCKvXLczK"
                       + "xbWF9KJa3hKQku9pvsqXMEZv8sWqJGDNl8vX2WU+jNvNNAwp9vhpkV3U2aJRGO59+vPx3dPZ4t3R/xMAAP//hiEOnwQwAAA="; }
        }
    }
}
