// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class update : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207131021373_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35hP69aP0q2VBXIb5rNe5P0j5+3ad/z55Vt9Erc2QvpvVsxfrxYcBIQA/WbV582FQTrLlrJjRfD7PmhYf/dDJajF4VtQ/FBQe33XStlEGSUEQBpM1Jv1Hkvj/S0m0U1zVPyz224jEz50UOhxeVk17QoB+LnE4ns3qvLG67YeGwjeimY8XFXkaFnfCvAwQuRUQX/n8nAhZF4GneTP9uUOiqn9uiSD9/9zQ4IdtIH/uvYTNJhqTkhVk/BQ7mhz6pHr6pGOjpfXrvO2YDeNbp64T8ePH9psOOYYghR5CH17n+9gQ7WDsd4/vSvyhHzy+OxCoPP4iW62I+l7gop+kryVqOdl+/f6hyUJg3J0GLk+X9LYnIn52kXe+heDMhF+fZm02ycAPJ7NFr9mNU2f6"
                       + "ic9g1wVzE2Dew+/KJd0Qzs52B4qj4zMa2oJcKh6ljpFwGojO9N3X06zM6ohXd1KV68VyyDPc9HbobPlwwm/eH6J4UDGI8s3tIVrL6QOzH94ejgtrfEDu09tDiigtH2Tk668B29PJUeDe933oj+92GK3Lz54a1JahmOj3Tk7eS4o2xDfvLUsbYd1Com54/+evXMUjlIDXoi2+Vg8DkhJr8LXgu9BiAL5r8LXg27BhALz9/vbQvym9ZoICH4z57PZQ+lFBdKRfg3Pj7v4m6NLia/RgfPmBSframPs++gbY7433N6Lrb4T+AVbqZ9WO9BzVbhPbu35i/7aOqjqJbCo2ptl7XqM0+Sglol0WM3iMr6+bNl+M0WD8+heVJ2WRQ4RMgy+yZXGeN+2b6m2OJQNyar9+qt7mxZpmVv6/NF9fYPQ35gPfM/kQy+4tL7N6Os/qrUX27s77BpCxjB1j/p6IdfIzXwdEN2/+dWAMxsMfRKThQP89wP5/Jbv984tv4z7aN4Bg1Df7ZuF288HfFNxOjveDwH4DeiHM2tZ5Vr43iL7/9Q0MLe52fZOAw9zqNwkzhuvXg/tNqMafHT3+frnKfl4sRNA6Yh2/YkOuUnykzz6aTSpCX9C8bSIzNAI3JjBjXXWaxEhjiWC/6+U4+y7i47uvSB6LhRD1MbFSceFAPCaYS9HNDqhpc7Y8r8xM01h9jEyTDiN8kbeUzGiz47otzrNpS19PSTdxbvsns3JNTU4Xk3x2tvxy3a7W7XHT5ItJee2P9/Hdzf1zIjfE+fGXKybbNzEEQpNZ+cvlk3VRzizez/qaawgEmFOtMWFFuX0Cd3FtIb2olrcEpOR7mq/yJWz5m3yxKglY8+XydXaZD+N2Mw1Dij1+WmQXdbZoFIZ7n/4k9pst3h39PwEAAP//++ZmjnEkAAA="; }
        }
    }
}
