// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class dalchanges2 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251030182_dalchanges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7n0jiu3npSD+v1U1fw0rs1mnYFhZQRKrHZAE0yfV0ycdxSKtX+dth9VN6Jq6TiRMHttvOiMaghR63314ne9vgOoUZAwz+12MUJYk9rvHdyVJoB88vjuQTXj8RbZa0Zx42QX9JH0tqYWT7dfvnz9Y"
                       + "CIy70yAo6U6g7YmmMLvIO9+CgWciwk+zNptkYJOT2aLX7EYGMP3E+aBrfRzxzXv4XXmtm2exPNOB4uj4jIa2IGvCo9QxEk4DKRR99/U0K7M6YtBOqnK9WA4ZxU1vh3bGhxN+8/4QxXbEIMo3t4dotb8PzH54ezjOFvmA3Ke3hxRR4z7IyNdfA7ZnpqLAve/70B/f7TBal589ZaotQzHR752cvJcUbchAvLcsbYR1C4m64f2fv3IVTSEErBZr8LXgD/FytMXX6sFG/gPw7fdfC7qL6QfAuwa3h/9N6TXjS/lgzGe3hxL3C6PDDVp8jR78cHyAnl8L/jeiOW+E/gE6/+dIKw8E2e+tiQfh3EILb3j3568G/uY8km9Kl/y/X4Zu1C4/a/rr/fTsz6qs90K8bhPbu35i/7YhnoZXItruvf4qci/ekiYfpUSey2KGWOv1ddPmizEajF//ovJ1XtMy+Uk+3sfat2n2RbYszvOmfVO9zSmZxt993eVom1Frmln5w1iTtnS/fX6xAF/cmEl8zyRWLC+4vMzq6Ryap5ejeb+kTCztx6N4TyQ76bqvA6KbN/w6MAaTbd8YwYZTil+zi1vnzTcENT+M3PnPX96OxkTfMK7xsOhnr5POqunPRhfdRdFvrI9vQNeEueg6z8r3BrEpqf6NDTUaHn3TfXzTGu1nXy3fWmf+HK41/vzVl9+EIf8GZPz/g3z9c6Rl3lsbvt+6XH/1JsTGBj1WaG9cl5N45LOPZpOK0BY8b7to11mM63XS+T7WVafJDR3ecj0vPib9utPLe6z39YO+x3df0XQXC5m6x8RSxYUD8ZhgLkUROKCmzdnyvDLMQwP0MTJNOrz1Rd5SOqnNjuu2OM+mLX09JceD15x/MivX0DuLST47W365blfr9rhp8sWkvPbH+/ju5v55UTPE+fGXK56cb2IIhCYL+ZfLJ+uinFm8n0UEYwAEREDNAGFFa+4E7uLaQnpRLW8JSMn3NF/lSxiR"
                       + "N/liVRKw5svl6+wyH8btZhqGFHv8tMgu6mzRKAz3Pv1J7DdbvDv6fwIAAP//PJ2JLSIvAAA="; }
        }
    }
}
