// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class modelchanges : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207230933080_modelchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdXt7ldnPzJT//80Uz8fuf9nSTN/Hdf5PQVx70eC+CNB/FkbzQ9dEN+T++/9iPv/f8r90L9Lp39/tobwnvy2/yN++/8pv/281Lb/XxG7++8vdj8Su29ssn4kdj/7KPwcZF82yyAwygricMWQOJ4+qZ4+6dg/af06bzusYRaW"
                       + "UteJLGKN7TcdkgxBCnPjfXid72+A6tIXMczsd7eCsrcByt6todzbAOXeraHsb4Cyf2so9zdAud+FYhjIsor97vFdWdrUDx7fHVgDffxFtloRc3trovpJ+loWRE+2X7//qudCYNydBkspXca2PRFrZxd551vI5Ey00tOszSYZxO1ktug1u1EwTD9x+QheCiygeQ+/qwx2V4etLHWgODo+o6EtyCrxKHWMhNPAwq+++3qalVkdMYwnVbleLId82k1vh/bKhxN+8/4QxQb1IZpvbg/Rpnx8YPbD28NxWR8fkPv09pAilskHGfn6a8D2LG8UuPd9H/rjux1G6/KzZ2S0ZSgm+r2Tk/eSog3rpu8tSxth3UKibnj/569cRRc+A1aLNfha8Id4Odria/Vg1ysH4NvvvxZ0txI5AN41uD38b0qvmXVGH4z57PZQ4q5udLhBi6/Rg7+IOEDPrwX/G9GcN0L/AJ3/c6SVB5YG31sTD8K5hRbe8O7PYw38/3qO/dnWXe/vk/2cylBvVe9rylAEzq1lKPruj2To/70y9HPKsb2VuK/JsRE4t+bY6Ls/fznW5vK7unMZ150/p/zTW1n7mvyjcHw4t+af6Ls/f/nn//0a7/8XnN9b3PqanB+Bc2vOj777I87//x7nf3PR9c+qTPSWDrpNbO/6if3bLh1o2l5EwL0nCw9MjUaXELp5fGnyUUqkuyxmyOG/vm7afDFGg/HrX1S+zuvLvD7Jx/vjHdfsi2xZnOdN+6Z6m9NiL393XBZZI6sk77VMYVd8m2ZWRhYpQFSrJCKJ+sfdZezULSm+ys89QQ0n9n3WvwvkdW5c6X7P9d5QxqWj5WVWT+eQ0N5y5vutoobi7o3iPZG08eXXB+Eiy68PI6IIvmGCxfTYB3WxeU3Z4+oNyfIf8fYm4B/K29Fc+zeMazzd/rPXic25/+x14fLu33Af34CuMTl4gVDnWfneIOJOwTc81Gja/Zvu45vWaD/7avnWOnMg"
                       + "tf0jfRkF/k3py//vMdTPipJ5f4fmPfm6l27+EV9vAv7zkK/fk6F62eAfMdQm4B/KUDa99kH4vecc9zK2P5rjTcA/dI7/P6M0/l/HqL0E648YdRPwHzEqevjmg7LNXGuzsRaBTua0w8I2wWtZXVKVqetEcqNj+43kXj/7aDapaCiCpv2yQ44u+DBn1O+k832sq06TGzp0AVdsRPa7+Jjs17fqZG9DJ3ubO9m7dSf3NnRyb3Mn927dyf6GTvY3d7J/607ub+jk/uZO7nc76a1F2O8e3xUw+gH92VtzeHz31ZreXog0PSYRLS4ciMcEcykazQE1bc6W55WReBqfj5Fp0lEIX+Qtrfq12XHdFufZtKWvp5T3olWRj9KfzMo1NTldTPLZ2fLLdbtat8dNky8m5bU/3sd3N/f/+G4P58dfrlhevokhEJqsNL9cPlkX5czi/SwSPw6AgFZSe0ZYvW5h1y6uLaQX1fKWgJR8T/NVvoQ1fJMvViUBa75cvs4u82HcbqZhSLHHT4vsos4WjcJw79OfxH6zxbuj/ycAAP//HS6HSa9QAAA="; }
        }
    }
}
