// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class viewmodel : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207261134405_viewmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7n0jiu3npSD+yHG4DRY/p1bqGzG4b0ivlF8D0mZFDQJlBalB7YWmiz6pnj7paGtp/TpvO/rD5ANS14nkHsb2m86whiCFIU0fXuf7G6A6qxPDzH4XI5Qlif3u8V3JvOgHj+8OpGgef5GtVjQnXspG"
                       + "P0lfS77mZPv1+ydlFgLj7jSI9LoTaHuiKcwu8s63EIWZ6MWnWZtNMrDJyWzRa3YjA5h+4nzQNemO+OY9/K681k1eWZ7pQHF0fEZDW5CJ5lHqGAmngbyUvvt6mpVZHfESTqpyvVgOeRqb3g6Ntw8n/Ob9IYpBjkGUb24P0ZpUH5j98PZwnIH3AblPbw8pYht9kJGvvwZsz9pEgXvf96E/vtthtC4/e8pUW4Ziot87OXkvKdqQ1nlvWdoI6xYSdcP7//+Tq9uOMOpeBawWa/AenBz1nAY62MjNt+jBplMG4NvvvxZ0lygZAO8a3B7+N6XXjC/lgzGf3R5K3MOMDjdo8TV68HMcA/T8WvC/Ec15I/QP0Pk/R1p5IHPx3pp4EM4ttPCGd3/+auBvziP5pnTJ//tl6Bba5f/r1uzDNPCGHr4ZSxEE8D6o4IsfsvbrBb3dJrZ3/cT+bYNeDThF2bn3JGTmsTca/HYjUGnyUUqEuixmiD5fXzdtvhijwfj1Lypf5/VlXp/k4/3xjmv2RbYszvOmfVO9zSlny98dl0XWSHz/XgG2Tdw2zayMhNcgqjUHkRDzh5HGLsAXNyas3zOdFEs/Ly+zejqHLu7lv94v4RXLLvMo3hPJTlb464Dopqe/DozBnO43RrDhzPXX7OLWyzMbwrwf8fYm4B/K21G7+g3jGjetP3uddBbnfza66K69f2N9fAO6JszO13lWvjeIuDPzDQ81GjB+03180xrtZ18t31pn/hwuaf/81ZffhCH/BmT8/4N8/fPB9vxsqstvQK1HFm9vAef9lm77C3whSjYKtFrsxqVbCdA++2g2qQhtwfO267qhY3njem6sq06TGzq85ZJvfEyrir/u9PIeS8L9KPjx3Vc03cVCpu4xsWZx4UA8JphL0YwOqGlztjyvDAfRAH2MTJMOg32Rt5RxbLPjui3Os2lLX0/JE6M4/aP0J7NyTU1OF5N8drb8ct2u1u1x0+SLSXntj/fx3c39"
                       + "87p3iPPjL1c8Od/EEAhN1npfLp+si3Jm8X4WEYwBEBABtYuE1esW9vHi2kJ6US1vCUjJ9zRf5UtY1Tf5YlUSsObL5evsMh/G7WYahhR7/LTILups0SgM9z79Sew3W7w7+n8CAAD//2s7aaSaMgAA"; }
        }
    }
}
