// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class new_dal1 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207232125420_new_dal1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7kGxLZ1i++ER4uel8P6/Q51vViHAKCtIQBVDElj6pHr6pKNHpPXrvO1wtolUU9eJRMVj+02HJEOQQme7D6/z/Q1QnT6MYWa/ixHKksR+9/iu5AT0g8d3B5IHj7/IViuaRC+ZoJ+kryWTcLL9+v3T"
                       + "BQuBcXcaxCDdCbQ90RRmF3nnW/DeTKTvadZmkwxsdTJb9JrdyACmnzgfdI2NI755D78rr3XTKpZnOlAcHZ/R0BZkPHiUOkbCaSBjou++nmZlVkfs10lVrhfLIRu46e3QrPhwwm/eH6KYihhE+eb2EK0X6wOzH94ejjM9PiD36e0hRTSwDzLy9deA7VmYKHDv+z70x3c7jNblZ0+ZasuO39SVk/eSog0Jh/eWpY2wbiFRN7z/81euohmDgNViDb4W/CFejrb4Wj3YQH8Avv3+a0F3IbyCH25we/jflF4zAboPxnx2eyhxly463KDF1+jBj74H6Pm14H8jmvNG6B+g83+OtPJATP3emngQzi208IZ3f/5q4G/OI7EBcVeXLN9Pl/y/X4Zu1C4frL9+VqW0F5x1m9je9RP7tw3ONDAKIjamSne5txcpSZOPUiLdZTFDlPT6umnzxRgNxq9/Ufk6r2k9+yQf72OR2jT7IlsW53nTvqne5pT14u++7rqxTX01zaz8f+nicQHLeUPK771TVrEE3vIyq6dz6IxeYuT98jGx/ByP4j2R7CwYfB0Q3QTf14ExmOH6xgg2nMf7ml3cOsG9IRz5EW9vAv6hvB2NZr5hXOMBzc9eJ53lzZ+NLrqrl99YH9+ArgmXJus8K98bxKZM9jc21Ghg80338U1rtJ99tXxrnflzuCj481dffhOGvLNO942N8f+DzP5DUT3vt0bWX0kJ8bVhjBXDG9fIJML47KPZpKKhCJq3XUALPaMbF85iXXWa3NDhLdfW4mPSrzu9vMfaWz+Me3z3FZmzYiFT95j4obhwIB4TzKWItgNq2pwtzyvDXjRAHyPTpMN9X+QtpXba7Lhui/Ns2tLXU3IleOn2J7NyDU2ymOSzs+WX63a1bo+bJl9Mymt/vI/vbu6fFxhDnB9/ueLJ+SaGQGiyhH65fLIuypnF+1lfNQ2BgAioYiesaOmawF1cW0gvquUtASn5nuarfAmz8CZf"
                       + "rEoC1ny5fJ1d5sO43UzDkGKPnxbZRZ0tGoXh3qc/if1mi3dH/08AAAD//9tIvv+dLgAA"; }
        }
    }
}
