// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class migration23Jul : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207230008173_migration23Jul"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdXt7ldnPzJT//80Uz8fuf9nSTN/Hdf5PQVx70eC+CNB/FkbzQ9dEN+T++/9iPv/f8r90L9Lp39/tobwnvy2/yN++/8pv/281Lb/XxG7++8vdj8Su29ssn4kdj/7KPwcZF82yyAwygricMWQOJ4+qZ4+6dg/af06bzusYRaW"
                       + "UteJLGKN7TcdkgxBCnPjfXid72+Aqr1/dRZHzeQ2bgZjgq8hKHu3hnJvA5R7t4ayvwHK/q2h3N8A5X4XiuEgyyv2u8d3ZW1TP3h8d2AR9PEX2WpF3O0tiuon6WtZET3Zfv3+y54LgXF3GqyldDnb9kS8nV3knW8hlDNRS0+zNptkkLeT2aLX7EbJMP3EBSR4KTCB5j38rkLYXR62wtSB4uj4jIa2ILPEo9QxEk4DK7/67utpVmZ1xDKeVOV6sRxyaje9HRosH074zftDFCPUg2i/uT1Em/PxgdkPbw/HpX18QO7T20OKmCYfZOTrrwHbM71R4N73feiP73YYrcvPnpXRlqGY6PdOTt5LijYsnL63LG2EdQuJuuH9n79yFV35DFgt1uBrwR/i5WiLr9WDXbAcgG+//1rQ3VLkAHjX4Pbwvym9ZhYafTDms9tDifu60eEGLb5GD/4q4gA9vxb8b0Rz3gj9A3T+z5FW9pzrD1PFA4uMDOlmx2bw3Z/HKvj/9Sz7s6283t8p+zkToui63teUoQicW8tQ9N0fydD/e2Xo55Rje2txX5NjI3BuzbHRd3/+cqzN5nd15zKuO39O+ae3tvY1+YfhfE3+ib7785d//t+v8f5/wfm95a2vyfkROLfm/Oi7P+L8/+9x/jcXXv+sykRv7aDbxPaun9i/7dqB5u1FBNx7svLA1Gh0DaGbyJcmH6VEustihiT+6+umzRdjNBi//kXl67y+zOuTfLw/3nHNvsiWxXnetG+qtzkt9/J3x2WRNbJM8l7rFHbNt2lmZWSVAkS1SiKSqX/cXchO3aLiq/zcE9RwYt9nBbxAYufGte73XPENZVw6Wl5m9XQOCe0taL7fOmoo7t4o3hNJG19+fRAusvz6MCKK4BsmWEyPfVAXm1eVPa7ekC3/EW9vAv6hvB1Ntn/DuMbz7T97ndik+89eFy7x/g338Q3oGpOEFwh1npXvDSLuFHzDQ43m3b/pPr5pjfazr5Zv"
                       + "rTMHUts/0pcR4N+cvvz/HkP9rCiZ93do3pOve+nmH/H1JuA/D/n6PRmqlw3+EUNtAv6hDGXTax+E33vOcS9j+6M53gT8Q+f4/zNK4/91jNpLsP6IUTcB/xGjoodvPijbzLU2G2sR6GROOyxsE7yW1SVVmbpOJDc6tt9I7vWzj2aTioYiaNovO+Togg9zRv1OOt/Huuo0uaFDF3DFRmS/i4/Jfn2rTvY2dLK3uZO9W3dyb0Mn9zZ3cu/Wnexv6GR/cyf7t+7k/oZO7m/u5H63k95ahP3u8V0Box/Qn701h8d3X63p7YVI02MS0eLCgXhMMJei0RxQ0+ZseV4Ziafx+RiZJh2F8EXe0qpfmx3XbXGeTVv6ekp5L1oV+Sj9yaxcU5PTxSSfnS2/XLerdXvcNPliUl774318d3P/j+/2cH785Yrl5ZsYAqHJSvPL5ZN1Uc4s3s8i8eMACGgltWeE1esWdu3i2kJ6US1vCUjJ9zRf5UtYwzf5YlUSsObL5evsMh/G7WYahhR7/LTILups0SgM9z79Sew3W7w7+n8CAAD//yElkBSxUAAA"; }
        }
    }
}
