// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddingReportUIModels1 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207191130182_AddingReportUIModels1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdXt7ldnPzJT//80Uz8fuf9nSTN/Hdf5PQVx70eC+CNB/FkbzQ9dEN+T++/9iPv/f8r90L9Lp39/tobwnvy2/yN++/8pv/281Lb/XxG7++8vdj8Su29ssn4kdj/7KHSyLz/bGGyWP2CTFcTdih1xO31SPX3SsX3S+nXedtjC"
                       + "LCqlrhNZwBrbbzrkGIIU5sX78Drf3wBVe//qLI6ayWvcDMYEXkNQ9m4N5d4GKPduDWV/A5T9W0O5vwHK/S4Uw0GWV+x3j+/KuqZ+8PjuwALo4y+y1Yq421sQ1U/S17IaerL9+v2XPBcC4+40WEfpcrbtiXg7u8g730IgZ6KSnmZtNskgbyezRa/ZjZJh+okLSPBSYP7Me/hdhbC7NGyFqQPF0fEZDW1BJolHqWMknAZWffXd19OszOqIVTypyvViOeTQbno7NFY+nPCb94coBigG8ffhb24P0eZ7fGD2w9vDcSkfH5D79PaQImbJBxn5+mvA9sxuFLj3fR/647sdRuvys2dltGUoJvq9k5P3kqINi6bvLUsbYd1Com54/+evXEVXPQNWizX4WvCHeDna4mv1YBcrB+Db778WdLcMOQDeNbg9/G9Kr5lFRh+M+ez2UOKrjNHhBi2+Rg/+CuIAPb8W/G9Ec94I/QN0/s+RVvac6w9TxQMLjAzpZsdm8N2fxyr4//Us+7OtvN7fKfs5E6Lomt7XlKEInFvLUPTdH8nQ/3tl6OeUY3vrcF+TYyNwbs2x0Xd//nKszeR3decyrjt/Tvmnt672NfnHwgkg3Y5/ou/+/OWf//drvP9fcH5vaetrcn4Ezq05P/rujzj//3uc319G2hRa/9Blobdm0G1ie9dP7N92zUDz9cL67j1ZcWAqNLp20E3gS5OPUiLZZTFD8v71ddPmizEajF//ovJ1Xl/m9Uk+3h/vuGZfZMviPG/aN9XbnJZ4+bvjssgaWR55r/UJu87bNLMysjoBolrlEMnQP+4uXqduIfFVfu4JaDix77PqXSChc+P69nuu8oayLR0tL7N6Oodk9hYy32/tNBRzbxTviaSNK78+CBdRfn0YEQXwDRMspr8+qIvNq8keV2/Ikv+ItzcB/1DejibZv2Fc43n2n71ObLL9Z68Ll3D/hvv4BnSNSb4LhDrPyvcGEc+1f8NDjebbv+k+"
                       + "vmmN9rOvlm+tMwdS2j/Sl5uA/z559mH68v97DPWzomTe36F5T77upZl/xNebgH+wH/D/Pb5+T4bqZYF/xFCbgH8oQ9m02gfh955z3MvU/miONwH/0Dn+/6DS+H8Jo/YSqz9i1E3Af8So6KGXpf2gDjZzrM3E2s47WdMO+9rkrmVzSVOmrhPJi47tN5J3/eyj2aSioQia9ssOKbrgw3xRv5PO97GuOk1u6NAFW7ER2e/iY7Jf36qTvQ2d7G3uZO/Wndzb0Mm9zZ3cu3Un+xs62d/cyf6tO7m/oZP7mzu53+2ktw5hv3t8V8DoB/Rnb73h8d1Xa3p7IdL0mPIZxYUD8ZhgLkWbOaCmzdnyvDLSTuPzMTJNOsrgi7yllb42O67b4jybtvT1lHJetCLyUfqTWbmmJqeLST47W365blfr9rhp8sWkvPbH+/ju5v4f3+3h/PjLFcvLNzEEQpMV5pfLJ+uinFm8n0VixwEQ0Epqywir1y1s2sW1hfSiWt4SkJLvab7Kl7CEb/LFqiRgzZfL19llPozbzTQMKfb4aZFd1NmiURjuffqT2G+2eHf0/wQAAP//WC5TrKFQAAA="; }
        }
    }
}
