// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class new_dal : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207232120041_new_dal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1NlbUFr/JVVf/Idfz/qbX6Zrw+6Lel028/PEL8vJTh/3do9c2aBBhlBQmoYkgCS59UT5909Ii0fp23Hc42AWvqOpHgeGy/6ZBkCFLoc/fhdb6/Aapqw6/OIpB6KjNKL0sZ+93ju5Ih0A8e3x1IJTz+IlutaC691IJ+kr6WvMLJ9uv3"
                       + "Tx4sBMbdaaDju/Noe6KZzC7yzrdgwZkI4dOszSYZuOtktug1u5EPTD9xdujaHDcH5j38rizXTbJY1ulAcXR8RkNbkA3hUeoYCaeB/Im++3qalVkdMWMnVbleLIdM4aa3Q+viwwm/eX+IYjFiEOWb20O0Pq0PzH54ezjOAvmA3Ke3hxRRxD7IyNdfA7ZnaKLAve/70B/f7TBal589naotO+5TV07eS4o2pB/eW5Y2wrqFRN3w/s9fuYrmDwJWizX4WvCHeDna4mv1YMP+Afj2+68F/WXVaEA/AN5F/LeH/03pNROu+2DMZ7eHEvfsosMNWnyNHvxYfICeXwv+N6I5b4T+ATr/50grO1fywzTx5kidAd6kjG8G8fNXH39z/omNkruaZfl+muX//RJ1o675YG32syqzvVCt28T2rp/Yv22opmFSEL8xVbpLwb24SZp8lBLpLosZYqbX102bL8ZoMH79i8rXeU1r3Sf5eB8L2KbZF9myOM+b9k31NqdUGH/3ddeUbT6saWbl/0sXlgvY0ddttTkP+J55rFhWb3mZ1dM5dEYvW/J+SZpY0o5H8Z5IdhYTvg6Ibtbv68AYTHt9YwQbTu59zS5unfzeEJz8iLc3Af9Q3o7GNt8wrvHw5mevk87S589GF92VzW+sj29A14TLlnWele8NYlN6+xsbajTM+ab7+KY12s++Wr61zvy5XzD8+as2vwl73lnD+8bG+P9Bnv+haKD3Wz/rL6+E+NpoRtvfYv1MAo3PPppNKhqKoHnbxbXQQbpxUS3WVafJDR3219Z6ffabxLr9xhbp+hHe47uvyNIVC5nOx8QjxYUD8ZhgLkXcHVDT5mx5XhmWo0H7GJkmHY78Im8pB9Rmx3VbnGfTlr6ekpfBS70/mZVraJfFJJ+dLb9ct6t1e9w0+WJSXvvjfXx3c/+8Ehni/PjLFU/YNzEEQpOl9svlk3VRzizez/rqaggExEJnlLCipW4Cd3FtIb2olrcEpOR7"
                       + "mq/yJUzFm3yxKglY8+XydXaZD+N2Mw1Dij1+WmQXdbZoFIZ7n/4k9pst3h39PwEAAP//KArNsdQuAAA="; }
        }
    }
}
