// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207111718162_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35hP69aP0q2VBXIb5rNe5P0j5+3ad/z55Vt9Erc2QvpvVsxfrxYcBIQA/WbV582FQTrLlrJjRfD7PmhYf/dDJajF4VtQ/FBQe33XStlEGSUEQBpM1Jv1Hkvj/S0m0U1zVPyz224jEz50UOhxeVk17QoB+LnE4ns3qvLG67YeGwjeimY8XFXkaFnfCvAwQuRUQX/n8nAhZF4GneTP9uUOiqn9uiSD9/9zQ4IdtIH/uvYRbm2h1k786+5F5DtDMWAX9/8RIfyNK+Rt2l38ki/IpFGRWEKcrdsT59En19ElHIKX167ztcIeJc1PXicTUY/tNhxxDkEJvvQ+v8/0NUK1i2YAaaZ0opSxN7HeP70pKQT94fHcg9/D4i2y1okn0chH6SfpaEhEn26/fP9uw"
                       + "EBh3p0EU051B2xPNYXaRd76FLZwJ2z/N2mySga1OZotesxs5wPQTZ4Su2nbEN+/hd2W2blbGMk0HiqPjMxragtQwj1LHSDgNJFz03dfTrMzqiCU4qcr1YjlkTTa9HapmH074zftDFH0bgyjf3B6i1bs+MPvh7eE41esDcp/eHlJE9/kgI19/Ddieao8C977vQ398t8NoXX72tKm27HggXTl5LynakLJ4b1naCOsWEnXD+z9/5SqedAh4Ldria/UwICmxBl8LvssWDMB3DRj++8K3mYAB8Pb720P/pvSaifN9MOaz20PpB/rRkX4Nzo1H8JugS4uv0YMJzwcm6Wtj7ofdG2C/N97fiK6/EfoHWKmfIzviub0fZjwGAnOGdEtXLPbuz47RiEXLPrTY97eH/s0bkG9Kgf0sOGY/PwWqF/l1m9je9RP7t438NOoS8XHv9Zeie2GYNPkoJaJdFjOEYK+vmzZfjNFg/PoXlSdlkcMmmQZfZMviPG/aN9XbHMvqFCV+/eVsm5xqmll5mzXtn4OVtAKjvzEp956poFhybXmZ1dN5Vm8tsnd33jexE0uYMebviVgnXfZ1QHSTZV8HxmCe6oOINJyAew+wt04vbwhhfsS33zTfxoOebwDBaLDzzcLtrpl+U3A766AfBPYb0AvhymadZ+V7g+gHNN/A0OJxzDcJOFx//CZhfnO4fhOq8WdHj99a4f4cruf9rCjb4XW496Dez57K/QZUwjfqKvx/jXOtv29Fu7tEEiJoQ4iQ3Tetfol3/9lHs0lF6Auat10aC92XG5fEYl11mtzQobcwNjQifLdhTLzgFpsAS2r7XW9RrR9CPb77isSvWMjUPSZVW1w4EI8J5lIEyQE1bc6W55XhJxqgj5Fp0mG3L/KWEiBtdly3xXk2benrKdluXpP9yaxcQ24Xk3x2tvxy3a7W7XHT5ItJee2P9/Hdzf3zymGI8+MvVzw538QQCE0WmC+XT9ZFObN4P+tL8RAI"
                       + "iIAqUMKK1qQJ3MW1hfSiWt4SkJLvab7Kl1C/b/LFqiRgzZfL19llPozbzTQMKfb4aZFd1NmiURjuffqT2G+2eHf0/wQAAP//zsXkgrUuAAA="; }
        }
    }
}
