// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class controllerchange : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251203196_controllerchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7n0jiu3npSD+v0M1b1YHwCgrSNgUQxI++qR6+qSjE6T167ztcKmJOlPXiUS4Y/tNhyRDkELHuQ+v8/0NUJ1ui2Fmv4sRypLEfvf4rsT3+sHjuwOJgMdfZKsVTaKXGNBP0teSFTjZfv3+of9CYNyd"
                       + "BvFEdwJtTzSF2UXe+Ra8NxPpe5q12SQDW53MFr1mNzKA6SfOB13D4Yhv3sPvymvdFInlmQ4UR8dnNLQFGQIepY6RcBrIfui7r6dZmdURW3RSlevFcsiebXo7NBE+nPCb94coaj8GUb65PUSruH1g9sPbw3FmxAfkPr09pIgG9kFGvv4asD0LEwXufd+H/vhuh9G6/OwpU23Z8YG6cvJeUrQhefDesrQR1i0k6ob3f/7KVTT6D1gt1uBrwR/i5WiLr9WDDdoH4NvvvxZ0F44PgHcNhuH/bOk1E2z7YMxnt4cSd+miww1afI0e/Eh6gJ5fC/43ojlvhP4BOv/nSCsPxMfvrYkH4dxCC2949+evBv7mPJJvSpf8v1+GbtQuH6y/flaltBecdZvY3vUT+7cNzjQwCiI2pkp36bYXKUmTj1Ii3WUxQ5T0+rpp88UYDcavf1H5Oq9pbfokH+9jwdk0+yJbFud5076p3uaUweLvvu4asE1jNc2s/H/pQnABy3lj+u49M0enZd5Lxi0vs3o6h87oJUbeLx8Ty7XxKN4TyU6O7OuA6Cbrvg6MwQzXN0aw4Tze1+zi1snqDeHIj3h7E/AP5e1oNPMN4xoPaH72OuksVf5sdNFdifzG+vgGdE24zFjnWfneIDZlsr+xoUYDm2+6j29ao/3sq+Vb68yfwwW+n7/68psw5N+AjP9/kK9/KFrm/ZbD+osmIb42YrESd+NymAQTn300m1Q0FEHztmtloRN04xpZrKtOkxs6vOUyWnxM+nWnl/dYZutHbI/vviLLVSxk6h4TPxQXDsRjgrkUKXZATZuz5Xll2IsG6GNkmnS474u8pSxOmx3XbXGeTVv6ekpeA6/S/mRWrqE0FpN8drb8ct2u1u1x0+SLSXntj/fx3c3981piiPPjL1c8Od/EEAhNltAvl0/WRTmzeD/rq5AhEBAB1eGEFa1SE7iLawvpRbW8JSAl39N8lS9hAd7ki1VJwJovl6+zy3wY"
                       + "t5tpGFLs8dMiu6izRaMw3Pv0J7HfbPHu6P8JAAD//yuz9ANULgAA"; }
        }
    }
}
