// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddingReportUIModels : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207191114002_AddingReportUIModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdXt7ldnPzJT//80Uz8fuf9nSTN/Hdd5syBCQWYFsbn2QGxPn1RPn3SkUVq/ztsOf5h4L3WdSGw5tt90hjQEKXRZ+/A6398AVXv/6iyOmlE5UUpZmtjvHt+V0Fo/eHx3IAZ//EW2WhFDeTG5fpK+loD8ZPv1+0fdC4Fxdxq4"
                       + "8t0ZtD3RHGYXeedb2MKZyODTrM0mGfjkZLboNbuRA0w/cUbo6mxHfPMefldm62YnLNN0oDg6PqOhLUgH8yh1jITTQOJB3309zcqsjpiBk6pcL5ZDpmTT26F29uGE37w/RNG4MYjyze0hWpXjA7Mf3h6O0zo+IPfp7SFF9LAPMvL114Dt2ZkocO/7PvTHdzuM1uVnT5tqy4770ZWT95KiDXH7e8vSRli3kKgb3v/5K1fRwDtgtViDrwV/iJejLb5WDzZeHoBvv/9a0F0kPADeNbg9/G9Kr5k41wdjPutBuXm0QaAbHW7Q4mv04AexA/T8WvC/Ec15I/QP0Pk/R1rZcyI/TBUPxLgM6WbHZvDdn8cq+P/1LPuzrbze3yn7WRWiXuzUbWJ710/s3zZ20rglCKh49N1FzV4gI00+SolEl8UMQczr66bNF2M0GL/+ReXrvKZV25N8vI+lWNPsi2xZnOdN+6Z6m1Nuh7/7uqujNsHTNLPy/6VLpAUM242JrfdMScTSVMvLrJ7OIdG9HMr7JU1iWSgexXsi2Um+fB0QLzqpl68DYzAN9Y0RbDjZ9jW7uHUa9+d4xfHnL29vWAb8xnDdtMr3s9FJZxHvZ6OL7hrdN9bHN6BrwgW4Os/K9waxafntGxvqhtW1b66Pb1qj/eyr5VvrzJ/Dpa+fx/ry/3sM9bOiZLprSTfDeL+VpP5yQ4iODSasMNy4kiR+/mcfzSYVYS143naZ6T2Xl2Jdve8KlF1kiozIfhcf04euT/Vjqcd3X5FNKRYyc49JVxcXDsRjgrkU+XJATZuz5XllmIfG52NkmnR464u8pexHmx3XbXGeTVv6ekr2nJdafzIr1xDnxSSfnS2/XLerdXvcNPliUl774318d3P/vAgX4vz4yxXPzTcxBEKTRfjL5ZN1Uc4s3s8icjEAAhKg2pWwoqVmAndxbSG9qJa3BKTke5qv8iV085t8sSoJWPPl8nV2mQ/jdjMNQ4o9flpkF3W2"
                       + "aBSGe5/+JPabLd4d/T8BAAD//1G5+mQILQAA"; }
        }
    }
}
