// <auto-generated />
namespace teamcanada.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class dalchanges : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251008488_dalchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozbPFtNsmc2ysTT+KD0ui4wQeZ2X5++J1c5DYPWR7Y96PCXM2us316uce/3so1d5sy7bxm9EzX6v/Dr4gD56WVervG6vX+Xn+mox+yi9G753t/uifc17B71/9tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmpazWc7YKxUerT69HSEe3t3ZAyHuZstl1WYtzXEP8Q6ap2U+RTugahB+3dbENh+lz4p3+ex5vrxo5xbpL7J35pP9nR3inq+WBbEZJrRe5/4o5e/b9f775Fl9E7k2Q/puVs9erBcfBoQA/GTV5s2HQTnJlrNiRhP6PGtafPTDp6tF4VlR/3BweHzXCdxGMSQdQShM1pj2Hwnj/z+F0c5xVf8cyoBD4ocmBRuxOJ7N6ryxyuXnBIeXVdOeEKAfPhLfiII+XlTkcVjkCfUyQORWQHwNBEBP82b6w6eHNyk/h0j80O3E/wvM5a1N1at8VdVt89XZj8zU/y/N1Dfj7kGxLT9Usf28FMT/t6rmr2FlNusUDCsrSGK1A5Jg+qR6+qSjWKT167ztsLoJXVPXiYTJY/tNZ0RDkELvuw+v8/0NUJ2CjGFmv4sRypLEfvf4riQJ9IPHdweyCY+/yFYrmhMvu6CfpK8ltXCy/fr9"
                       + "8wcLgXF3GgQl3Qm0PdEUZhd551sw8ExE+GnWZpMMbHIyW/Sa3cgApp84H3StjyO+eQ+/K6918yyWZzpQHB2f0dAWZE14lDpGwmkghaLvvp5mZVZHDNpJVa4XyyGjuOnt0M74cMJv3h+i2I4YRPnm9hCtW+sDsx/eHo6zRT4g9+ntIUXUuA8y8vXXgO2ZqShw7/s+9Md3O4zW5WdPmWrLUEz0eycn7yVFGzIQ7y1LG2HdQqJueP/nr1xFUwgBq8UafC34Q7wcbfG1erCR/wB8+/3Xgu5i+gHwrsHt4X9Tes34Uj4Y89ntocT9wuhwgxZfowc/HB+g59eC/41ozhuhf4DO/znSygNB9ntr4kE4t9DCG979+auBvzmPxEbIXV2yfD9d8v9+GbpRu/ys6a/307M/q7LeC/G6TWzv+on924Z4Gl6JaLv3+qvIvXhLmnyUEnkuixlirdfXTZsvxmgwfv2Lytd5TcvkJ/l4H2vfptkX2bI4z5v2TfU2p2Qaf/d1l6NtRq1pZuUPY03a0v32+cUCfHFjJvE9k1ixvODyMqunc2ieXo7m/ZIysbQfj+I9keysQ3wdEN284deBMZhs+8YINpxS/Jpd3DpvviGo+WHkzn/+8nY0JvqGcY2HRT97nXRWTX82uuguin5jfXwDuibMRdd5Vr43iE1J9W9sqNHw6Jvu45vWaD/7avnWOvPncK3x56++/CYMeWf57+uA+P8gX/8caZn31obvty7XX70JsbFBjxXaG9flJB757KPZpCK0Bc/bLtp1FuN6nXS+j3XVaXJDh7dcz4uPSb/u9PIe6339oO/x3Vc03cVCpu4xsVRx4UA8JphLUQQOqGlztjyvDPPQAH2MTJMOb32Rt5ROarPjui3Os2lLX0/J8eA155/MyjX0zmKSz86WX67b1bo9bpp8MSmv/fE+vru5f17UDHF+/OWKJ+ebGAKhyUL+5fLJuihnFu9nEcEYAAERUDNAWNGaO4G7uLaQXlTL"
                       + "WwJS8j3NV/kSRuRNvliVBKz5cvk6u8yHcbuZhiHFHj8tsos6WzQKw71PfxL7zRbvjv6fAAAA//8ZL6ljIi8AAA=="; }
        }
    }
}
