// <auto-generated />
namespace DemoApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207071044130_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Y227bOBB9X6D/IOip+1DTzQJFG8gtsnayMHadFFHad1oaOcTyoiWpwP62PvST+gs71F2yfGuTvRR9k6iZMxcezgz15dPn4N1acO8BtGFKTvyXo7HvgYxUzORq4mc2efHaf/f22U/BZSzW3sdK7szJoaY0E//e2vScEBPdg6BmJFiklVGJHUVKEBorcjYevyYvxwQQwkcszwtuM2mZgPwFX6dKRpDajPKFioGbch2/hDmqd00FmJRGMPFnINRFmnIWUYu+jAoN37vgjKI3IfDkRNfGb5xrfm0UzV6ie3Zzt0khNz3xL9fRPZUruKUW2pIo+ztsOgu49F6rFLTd3EJS6rPY90hXj/QVa7WWjnNh4s+l/eXM964zzumS40JCuQHfS1+dh1Zp+A0kaPQsfk+tBY0bNI8hD6FMxXn66rhsvCHjM5cNQqVUNs/wluM9NxOtxDTTGmmzqRwOrUYC+d4VW0P8B8iVva+dXtB1tYKPvvdBMuQbKlmdQTvI4n2/cav+NdMu4ZXRmcpQb2CH2hABaWh1FNk+zH9QreMmFQoLx0lJ/8HXyjSmXuBOmSc2vJ/lWOktZUihHtVnyx7VC/EQbCkIrQKMITQ2ipI/6hTofib6YM0B2weFx28wsjqGpk2Rok9V/YzsaGjBgqYpJr3V4MoVLyy62/RFeHr3EgUGicxAE6u9rS3hMaYr6H1F0+jpFdPGzqilS+poMI3FltjhHasMDW1cv3w1ya+03HOhOdzpR7tbcTuhVxijo3seLtS+7evkJUAYUU71QIGcKp4JuavI7tPulpw2TvfL8YjtOtLGa68fj1a0sjaOHjhGBbV7+e1vKNna0V4r6tPkKBK1D+wjUqjfYE8i0JDy09CnantthGrt+yFh05/aWM3qP0zGrWrfF6mt11W/V92DstIevtNsld5CxPcwRQ8sdmU33BgLYuQERuFffMoZuO2vBBZUsgSMvVN/grufYWf4+itRPZkZ"
                       + "E/P/8r2IuRQcHEsfYT6UD1RjoPq5oOufv33m+ya49r0j4Yra7+Ha8SQ72b0uHJOr/x8b+lP9CWCnTerb4+FxM3YxkB+Y14t6N/HjpcJACocvuxP/0SP9gYl+n6n8PvCVI/92sQ9I+zdXMAPDVg2E++klIXJjSQNaycxloqqNxhjbHlUiPR4swNIYd+ZCW5bQyOLnCIzJb3gfKc9clGIJ8VzeZDbN7IUxIJa806EDst9+fq/p+hzcpO7NPEYI6CbDEOBG/poxHtd+Xw3UtB0QjqRlAUGv8IaLcKtNjXSt5JFAZfpmkIJ05ecORModEW9kSB9gt2+Hc9jNWDBjdKWpMCVGo+/+uhL32/Xt3xlwaq+oFQAA"; }
        }
    }
}
