//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("toronto", "WardCandidate", "Ward", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Ward), "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Candidate))]
[assembly: EdmRelationshipAttribute("toronto", "CandidateContribution", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(teamcanada.Candidate), "Contribution", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Contribution), true)]
[assembly: EdmRelationshipAttribute("toronto", "ContributorContribution", "Contributor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(teamcanada.Contributor), "Contribution", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Contribution), true)]
[assembly: EdmRelationshipAttribute("toronto", "CandidateElection", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Candidate), "Election", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Election))]
[assembly: EdmRelationshipAttribute("toronto", "ElectionContributor", "Election", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Election), "Contributor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(teamcanada.Contributor))]

#endregion

namespace teamcanada
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class torontoContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new torontoContainer object using the connection string found in the 'torontoContainer' section of the application configuration file.
        /// </summary>
        public torontoContainer() : base("name=torontoContainer", "torontoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new torontoContainer object.
        /// </summary>
        public torontoContainer(string connectionString) : base(connectionString, "torontoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new torontoContainer object.
        /// </summary>
        public torontoContainer(EntityConnection connection) : base(connection, "torontoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ward> Wards
        {
            get
            {
                if ((_Wards == null))
                {
                    _Wards = base.CreateObjectSet<Ward>("Wards");
                }
                return _Wards;
            }
        }
        private ObjectSet<Ward> _Wards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidate>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidate> _Candidates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contribution> Contributions
        {
            get
            {
                if ((_Contributions == null))
                {
                    _Contributions = base.CreateObjectSet<Contribution>("Contributions");
                }
                return _Contributions;
            }
        }
        private ObjectSet<Contribution> _Contributions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Election> Elections
        {
            get
            {
                if ((_Elections == null))
                {
                    _Elections = base.CreateObjectSet<Election>("Elections");
                }
                return _Elections;
            }
        }
        private ObjectSet<Election> _Elections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contributor> Contributors
        {
            get
            {
                if ((_Contributors == null))
                {
                    _Contributors = base.CreateObjectSet<Contributor>("Contributors");
                }
                return _Contributors;
            }
        }
        private ObjectSet<Contributor> _Contributors;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Wards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWards(Ward ward)
        {
            base.AddObject("Wards", ward);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contributions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContributions(Contribution contribution)
        {
            base.AddObject("Contributions", contribution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Elections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToElections(Election election)
        {
            base.AddObject("Elections", election);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contributors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContributors(Contributor contributor)
        {
            base.AddObject("Contributors", contributor);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="toronto", Name="Candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="numVotes">Initial value of the numVotes property.</param>
        /// <param name="totalContributions">Initial value of the totalContributions property.</param>
        public static Candidate CreateCandidate(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.Int32 numVotes, global::System.Decimal totalContributions)
        {
            Candidate candidate = new Candidate();
            candidate.Id = id;
            candidate.firstName = firstName;
            candidate.lastName = lastName;
            candidate.numVotes = numVotes;
            candidate.totalContributions = totalContributions;
            return candidate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numVotes
        {
            get
            {
                return _numVotes;
            }
            set
            {
                OnnumVotesChanging(value);
                ReportPropertyChanging("numVotes");
                _numVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numVotes");
                OnnumVotesChanged();
            }
        }
        private global::System.Int32 _numVotes;
        partial void OnnumVotesChanging(global::System.Int32 value);
        partial void OnnumVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totalContributions
        {
            get
            {
                return _totalContributions;
            }
            set
            {
                OntotalContributionsChanging(value);
                ReportPropertyChanging("totalContributions");
                _totalContributions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalContributions");
                OntotalContributionsChanged();
            }
        }
        private global::System.Decimal _totalContributions;
        public string candidateLastName;
        public string candidateFirstName;
        partial void OntotalContributionsChanging(global::System.Decimal value);
        partial void OntotalContributionsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "WardCandidate", "Ward")]
        public EntityCollection<Ward> Wards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ward>("toronto.WardCandidate", "Ward");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ward>("toronto.WardCandidate", "Ward", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "CandidateContribution", "Contribution")]
        public EntityCollection<Contribution> Contributions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contribution>("toronto.CandidateContribution", "Contribution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contribution>("toronto.CandidateContribution", "Contribution", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "CandidateElection", "Election")]
        public EntityCollection<Election> Elections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Election>("toronto.CandidateElection", "Election");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Election>("toronto.CandidateElection", "Election", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="toronto", Name="Contribution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contribution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contribution object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="amount">Initial value of the amount property.</param>
        /// <param name="contributionType">Initial value of the contributionType property.</param>
        /// <param name="contributorType">Initial value of the contributorType property.</param>
        /// <param name="candidateId">Initial value of the CandidateId property.</param>
        /// <param name="contributorId">Initial value of the ContributorId property.</param>
        public static Contribution CreateContribution(global::System.Int32 id, global::System.Decimal amount, global::System.String contributionType, global::System.String contributorType, global::System.Int32 candidateId, global::System.Int32 contributorId)
        {
            Contribution contribution = new Contribution();
            contribution.Id = id;
            contribution.amount = amount;
            contribution.contributionType = contributionType;
            contribution.contributorType = contributorType;
            contribution.CandidateId = candidateId;
            contribution.ContributorId = contributorId;
            return contribution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Decimal _amount;
        partial void OnamountChanging(global::System.Decimal value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contributionType
        {
            get
            {
                return _contributionType;
            }
            set
            {
                OncontributionTypeChanging(value);
                ReportPropertyChanging("contributionType");
                _contributionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contributionType");
                OncontributionTypeChanged();
            }
        }
        private global::System.String _contributionType;
        partial void OncontributionTypeChanging(global::System.String value);
        partial void OncontributionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contributorType
        {
            get
            {
                return _contributorType;
            }
            set
            {
                OncontributorTypeChanging(value);
                ReportPropertyChanging("contributorType");
                _contributorType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contributorType");
                OncontributorTypeChanged();
            }
        }
        private global::System.String _contributorType;
        partial void OncontributorTypeChanging(global::System.String value);
        partial void OncontributorTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CandidateId
        {
            get
            {
                return _CandidateId;
            }
            set
            {
                OnCandidateIdChanging(value);
                ReportPropertyChanging("CandidateId");
                _CandidateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateId");
                OnCandidateIdChanged();
            }
        }
        private global::System.Int32 _CandidateId;
        partial void OnCandidateIdChanging(global::System.Int32 value);
        partial void OnCandidateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContributorId
        {
            get
            {
                return _ContributorId;
            }
            set
            {
                OnContributorIdChanging(value);
                ReportPropertyChanging("ContributorId");
                _ContributorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContributorId");
                OnContributorIdChanged();
            }
        }
        private global::System.Int32 _ContributorId;
        partial void OnContributorIdChanging(global::System.Int32 value);
        partial void OnContributorIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "CandidateContribution", "Candidate")]
        public Candidate Candidate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("toronto.CandidateContribution", "Candidate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("toronto.CandidateContribution", "Candidate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candidate> CandidateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("toronto.CandidateContribution", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candidate>("toronto.CandidateContribution", "Candidate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "ContributorContribution", "Contributor")]
        public Contributor Contributor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contributor>("toronto.ContributorContribution", "Contributor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contributor>("toronto.ContributorContribution", "Contributor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contributor> ContributorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contributor>("toronto.ContributorContribution", "Contributor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contributor>("toronto.ContributorContribution", "Contributor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="toronto", Name="Contributor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contributor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contributor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="postCode">Initial value of the postCode property.</param>
        /// <param name="relationship">Initial value of the relationship property.</param>
        public static Contributor CreateContributor(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.Int32 postCode, global::System.String relationship)
        {
            Contributor contributor = new Contributor();
            contributor.Id = id;
            contributor.firstName = firstName;
            contributor.lastName = lastName;
            contributor.postCode = postCode;
            contributor.relationship = relationship;
            return contributor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 postCode
        {
            get
            {
                return _postCode;
            }
            set
            {
                OnpostCodeChanging(value);
                ReportPropertyChanging("postCode");
                _postCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postCode");
                OnpostCodeChanged();
            }
        }
        private global::System.Int32 _postCode;
        partial void OnpostCodeChanging(global::System.Int32 value);
        partial void OnpostCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String relationship
        {
            get
            {
                return _relationship;
            }
            set
            {
                OnrelationshipChanging(value);
                ReportPropertyChanging("relationship");
                _relationship = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("relationship");
                OnrelationshipChanged();
            }
        }
        private global::System.String _relationship;
        partial void OnrelationshipChanging(global::System.String value);
        partial void OnrelationshipChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "ContributorContribution", "Contribution")]
        public EntityCollection<Contribution> Contributions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contribution>("toronto.ContributorContribution", "Contribution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contribution>("toronto.ContributorContribution", "Contribution", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "ElectionContributor", "Election")]
        public EntityCollection<Election> Elections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Election>("toronto.ElectionContributor", "Election");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Election>("toronto.ElectionContributor", "Election", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="toronto", Name="Election")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Election : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Election object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="electionType">Initial value of the electionType property.</param>
        /// <param name="year">Initial value of the year property.</param>
        /// <param name="totalNumVotes">Initial value of the totalNumVotes property.</param>
        /// <param name="totalNumCandidates">Initial value of the totalNumCandidates property.</param>
        public static Election CreateElection(global::System.Int32 id, global::System.String electionType, global::System.DateTime year, global::System.Int32 totalNumVotes, global::System.Int32 totalNumCandidates)
        {
            Election election = new Election();
            election.Id = id;
            election.electionType = electionType;
            election.year = year;
            election.totalNumVotes = totalNumVotes;
            election.totalNumCandidates = totalNumCandidates;
            return election;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String electionType
        {
            get
            {
                return _electionType;
            }
            set
            {
                OnelectionTypeChanging(value);
                ReportPropertyChanging("electionType");
                _electionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("electionType");
                OnelectionTypeChanged();
            }
        }
        private global::System.String _electionType;
        partial void OnelectionTypeChanging(global::System.String value);
        partial void OnelectionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private global::System.DateTime _year;
        partial void OnyearChanging(global::System.DateTime value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 totalNumVotes
        {
            get
            {
                return _totalNumVotes;
            }
            set
            {
                OntotalNumVotesChanging(value);
                ReportPropertyChanging("totalNumVotes");
                _totalNumVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalNumVotes");
                OntotalNumVotesChanged();
            }
        }
        private global::System.Int32 _totalNumVotes;
        partial void OntotalNumVotesChanging(global::System.Int32 value);
        partial void OntotalNumVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 totalNumCandidates
        {
            get
            {
                return _totalNumCandidates;
            }
            set
            {
                OntotalNumCandidatesChanging(value);
                ReportPropertyChanging("totalNumCandidates");
                _totalNumCandidates = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalNumCandidates");
                OntotalNumCandidatesChanged();
            }
        }
        private global::System.Int32 _totalNumCandidates;
        public int ElectionYear;
        partial void OntotalNumCandidatesChanging(global::System.Int32 value);
        partial void OntotalNumCandidatesChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "CandidateElection", "Candidate")]
        public EntityCollection<Candidate> Candidates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate>("toronto.CandidateElection", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate>("toronto.CandidateElection", "Candidate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "ElectionContributor", "Contributor")]
        public EntityCollection<Contributor> Contributors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contributor>("toronto.ElectionContributor", "Contributor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contributor>("toronto.ElectionContributor", "Contributor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="toronto", Name="Ward")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ward : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ward object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="wardNum">Initial value of the wardNum property.</param>
        /// <param name="numCandidates">Initial value of the numCandidates property.</param>
        /// <param name="wardName">Initial value of the wardName property.</param>
        /// <param name="numWardVotes">Initial value of the numWardVotes property.</param>
        /// <param name="totalWardContributions">Initial value of the totalWardContributions property.</param>
        public static Ward CreateWard(global::System.Int32 id, global::System.Int32 wardNum, global::System.Int32 numCandidates, global::System.String wardName, global::System.Int32 numWardVotes, global::System.Decimal totalWardContributions)
        {
            Ward ward = new Ward();
            ward.Id = id;
            ward.wardNum = wardNum;
            ward.numCandidates = numCandidates;
            ward.wardName = wardName;
            ward.numWardVotes = numWardVotes;
            ward.totalWardContributions = totalWardContributions;
            return ward;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wardNum
        {
            get
            {
                return _wardNum;
            }
            set
            {
                OnwardNumChanging(value);
                ReportPropertyChanging("wardNum");
                _wardNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wardNum");
                OnwardNumChanged();
            }
        }
        private global::System.Int32 _wardNum;
        partial void OnwardNumChanging(global::System.Int32 value);
        partial void OnwardNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numCandidates
        {
            get
            {
                return _numCandidates;
            }
            set
            {
                OnnumCandidatesChanging(value);
                ReportPropertyChanging("numCandidates");
                _numCandidates = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numCandidates");
                OnnumCandidatesChanged();
            }
        }
        private global::System.Int32 _numCandidates;
        partial void OnnumCandidatesChanging(global::System.Int32 value);
        partial void OnnumCandidatesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String wardName
        {
            get
            {
                return _wardName;
            }
            set
            {
                OnwardNameChanging(value);
                ReportPropertyChanging("wardName");
                _wardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("wardName");
                OnwardNameChanged();
            }
        }
        private global::System.String _wardName;
        partial void OnwardNameChanging(global::System.String value);
        partial void OnwardNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numWardVotes
        {
            get
            {
                return _numWardVotes;
            }
            set
            {
                OnnumWardVotesChanging(value);
                ReportPropertyChanging("numWardVotes");
                _numWardVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numWardVotes");
                OnnumWardVotesChanged();
            }
        }
        private global::System.Int32 _numWardVotes;
        partial void OnnumWardVotesChanging(global::System.Int32 value);
        partial void OnnumWardVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totalWardContributions
        {
            get
            {
                return _totalWardContributions;
            }
            set
            {
                OntotalWardContributionsChanging(value);
                ReportPropertyChanging("totalWardContributions");
                _totalWardContributions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalWardContributions");
                OntotalWardContributionsChanged();
            }
        }
        private global::System.Decimal _totalWardContributions;
        partial void OntotalWardContributionsChanging(global::System.Decimal value);
        partial void OntotalWardContributionsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("toronto", "WardCandidate", "Candidate")]
        public EntityCollection<Candidate> Candidates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate>("toronto.WardCandidate", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate>("toronto.WardCandidate", "Candidate", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
